config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/', to: 'users#home', as: 'home'

  get 'users', to: 'users#index', as: 'users'

  get 'users/show/:id', to: 'users#show', as: 'user'

  get 'admin', to: 'users#admin_index', as: 'users_admin'

  get 'users/edit', to: 'users/registrations#edit', as: 'edit_page'

  post 'users/edit/:id', to: 'users#leave', as: 'leave_team'

  patch 'code/:access_level', to: 'users#change_code', as: 'change_code'

  get 'users/EAB_roster', to: 'users#spreadsheet', as: 'users_spreadsheet'

  get 'users/clear', to: 'users#clear', as: 'users_clear'

  get 'teams', to: 'teams#index', as: 'teams'

  get 'teams/show/:id', to: 'teams#show', as: 'team'

  get 'teams/create', to: 'teams#create', as: 'team_create'

  post 'teams/create', to: 'teams#new_team', as: 'new_team'

  patch 'teams/add_member/:id', to: 'teams#add_member', as: 'add_member'

  patch 'teams/promote_to_leader/:id/:user_id', to: 'teams#promote_to_leader', as: 'promote_to_leader'

  get 'teams/edit/:id', to: 'teams#edit', as: 'edit_team'

  patch 'teams/update/:id', to: 'teams#update', as: 'update_team'

  delete 'teams/delete/:id', to: 'teams#delete', as: 'delete_team'

  resources :announcements

  patch '/users/admin/:id', to: 'users#make_admin', as: 'make_admin'

  patch '/users/superadmin/:id', to: 'users#make_super', as: 'make_super'

  patch '/users/regular/:id', to: 'users#make_regular', as: 'make_regular'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @announcements = Announcement.all.order("created_at DESC")
  end

  def show
    @announcement = Announcement.find(params[:id])
  end

  def new
    @announcement = Announcement.new
  end

  def create
    if !(content_params["title"].blank? || content_params["description"].blank?)
      @announcement = Announcement.new(content_params)
      @announcement.save!
    end
    redirect_to announcements_path
  end

  def edit
  end

  def update
    if @announcement.update(content_params)
      redirect_to announcement_path
    end
  end

  def destroy
    @announcement.destroy
    redirect_to announcements_path
  end

  private
    def content_params
      params.require(:announcement).permit(:title, :description)
    end

    def find_message
      @announcement = Announcement.find(params[:id])
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.haml
= simple_form_for(@announcement, html: { class: 'form-horizontal' }) do |f|  
  = f.input :title, label: "Title", input_html: { maxlength: 17 }, include_blank: false
  = f.input :description, label: "Description", input_html: { maxlength: 500 }, include_blank: false
  &nbsp
  = f.button :submit, class: %w[button btn btn-outline-success]

app/views/announcements/edit.html.haml
.content
  = render :partial => 'users/nav_bar', :locals => { :current_user => current_user }


%ul#details
  = @message

- if current_user.admin?
  %div.container{ align: "center" }
    %h4 Edit Announcement
    = render 'form'
    &nbsp
    = button_to "Cancel", announcements_path, class: %w[button btn btn-outline-success]
- else
  %div.ann-tile
    %h3{ align: "center" } Restricted Access!
    %a.ann-tile-link{:href => announcements_path}
      %div.container{ align: "center"}
        &nbsp
        = button_to "Back", announcements_path, class: %w[button btn btn-outline-success]

app/views/announcements/index.html.haml
.content
  = render :partial => 'users/nav_bar', :locals => { :current_user => current_user }

.content
  = render :partial => 'users/flash_messages', :locals => { :flash => flash }

%ul#details
  = @message

%div.container.title-container
  %h2 Dashboard

%div.container
  - @announcements.each_slice(4) do |slice|
    %div.row
      - slice.each do |announcement|
        %div.ann-tile-wrapper.col-md-3.col-md-3

          %div.ann-tile

            %a.ann-tile-link{:href => announcement_path(announcement)}
              %div.user-tile-img-overlay
                %p Take a look!

              %div.user-tile-info
                &nbsp              

                %h4{align: "center"}= announcement.title
                
                &nbsp

                %div.container 
                  &nbsp

                %div.container{ align: "center" }
                  &nbsp

                  = link_to "View", announcement_path(announcement), { class: 'btn btn-primary'}
  &nbsp

%div.container
  &nbsp

  - if current_user.admin?
    %h6{align: "left"}= button_to "Make Announcement", new_announcement_path, method: :get, class: %w[button btn btn-outline-success my-2 my-sm-0]

app/views/announcements/new.html.haml
.acontent
  = render :partial => 'users/nav_bar', :locals => { :current_user => current_user }


%ul#details
  = @message

- if current_user.admin?
  %div.container{ align: "center" }
    %h4 Make an Announcement
    = render 'form'
    &nbsp
    = button_to "Cancel", announcements_path, class: %w[button btn btn-outline-success]
- else
  %div.ann-tile
    %h3{ align: "center"} Restricted Access!
    %a.ann-tile-link{:href => announcements_path}
      %div.container{ align: "center"}
        &nbsp
        = button_to "Back", announcements_path, class: %w[button btn btn-outline-success]

app/views/announcements/show.html.haml
.page_format{:style => " margin-left: 15px;"}

.content
  = render :partial => 'users/nav_bar', :locals => { :current_user => current_user }

.content
  = render :partial => 'users/flash_messages', :locals => { :flash => flash }

%div.container.title-container
  %h2= @announcement.title

  %div.container
    &nbsp
    %p= @announcement.description

  &nbsp

%div.container
  - if current_user.admin?
    = link_to "Edit", edit_announcement_path(@announcement), class: %w[button btn btn-outline-success]
    &nbsp &nbsp
    = link_to "Delete", announcement_path(@announcement), method: :delete, data: { confirm: "Are you sure?" }, class: %w[button btn btn-outline-success]
  &nbsp &nbsp &nbsp &nbsp
  = link_to "Back", announcements_path, class: %w[button btn btn-outline-success]