config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/', to: 'users#home', as: 'home'

  get 'users', to: 'users#index', as: 'users'

  get 'users/show/:id', to: 'users#show', as: 'user'

  get 'admin', to: 'users#admin_index', as: 'users_admin'

  get 'users/edit', to: 'users/registrations#edit', as: 'edit_page'

  post 'users/edit/:id', to: 'users#leave', as: 'leave_team'

  patch 'code/:access_level', to: 'users#change_code', as: 'change_code'

  get 'users/EAB_roster', to: 'users#spreadsheet', as: 'users_spreadsheet'

  get 'users/clear', to: 'users#clear', as: 'users_clear'

  get 'teams', to: 'teams#index', as: 'teams'

  get 'teams/show/:id', to: 'teams#show', as: 'team'

  get 'teams/create', to: 'teams#create', as: 'team_create'

  post 'teams/create', to: 'teams#new_team', as: 'new_team'

  patch 'teams/add_member/:id', to: 'teams#add_member', as: 'add_member'

  patch 'teams/promote_to_leader/:id/:user_id', to: 'teams#promote_to_leader', as: 'promote_to_leader'

  get 'teams/edit/:id', to: 'teams#edit', as: 'edit_team'

  patch 'teams/update/:id', to: 'teams#update', as: 'update_team'

  delete 'teams/delete/:id', to: 'teams#delete', as: 'delete_team'

  resources :announcements

  patch '/users/admin/:id', to: 'users#make_admin', as: 'make_admin'

  patch '/users/superadmin/:id', to: 'users#make_super', as: 'make_super'

  patch '/users/regular/:id', to: 'users#make_regular', as: 'make_regular'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	validates :sid, uniqueness: true
	validates :first, :last, :email, :sid, presence: true
  validate :correct_access_code


  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "https://profilepicturesdp.com/wp-content/uploads/2018/06/default-good-youtube-profile-pictures-3.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    validates_attachment_size :image, :less_than => 5.megabytes

  belongs_to :team

  scope :search_team_name, lambda { |search|
    joins(:team).where("lower(name) LIKE lower(?)", "%#{search}%").order(:first)}



  ##Custom Validation methods
  def correct_access_code
    if self.code != Code.regular_code && self.code != Code.admin_code && self.code != Code.superadmin_code
      errors.add(:code, "-- Wrong access code")
    end
  end

  ##Methods dealing with user images
  def picture_missing?
    self.image.url.include?("https://profilepicturesdp.com/wp-content/uploads/2018/06/default-good-youtube-profile-pictures-3.jpg")
  end

  ##Methods dealing with access codes

  #to tell whether a user is an admin
  def admin?
    self.code == Code.admin_code or self.code == Code.superadmin_code
  end

  def superadmin?
    self.code == Code.superadmin_code
  end

  #to change an access code, as well as current members' access code (if having corresponding code)
  def self.change_code(type, newCode)
    old_code = Code.get_code(type)

    if newCode == old_code
      return Code.changing_to_same_value(type, newCode)
    end

    Code.set_code(type, newCode)
    User.where(code: old_code).update_all(code: newCode)

    return Code.changed_successful_message(type, old_code, newCode)
  end

  ##Methods dealing with search
  @@member = ["first", "last", "team", "major", "skillset", "year"]
  @@admin_only = ["email", "sid", "code"]

  # Search by keyword, phrase or alphabetically order by first name by default
  def search(search, admin)
    if !search.blank?
      @results = []
      if !search.strip.include? " "
        @results = self.search_keyword(search, admin)
      else
        @results = self.search_phrase(search, admin)
      end
    end
  end

  # Search keyword within respective member or admin fields
  def search_keyword(search, admin)
    permissions = admin ? @@member + @@admin_only : @@member
    @results = []

    for col in permissions
      self.update_results(col, search)
    end
    @results
  end

  # Search for a phrase within respective member or admin fields
  def search_phrase(search, admin)
    search = search.split(" ")
    permissions = admin ? @@member + @@admin_only : @@member
    @results = []

    for col in permissions
      for word in search
        self.update_results(col, word)
      end
    end
    @results
  end

  #generalize updating @results for search
  def update_results(column, search)
    if column == "team"
      find = User.search_team_name(search)
    else
      find = User.where("lower(#{column}) LIKE lower(?)", "%#{search}%").order(:first)
    end

    @results = @results | find
  end

  ##Methods dealing with download-roster
  def access
    case self.code
    when Code.regular_code
      return "regular"
    when Code.admin_code
      return "admin"
    when Code.superadmin_code
      return "super-admin"
    end
  end

  ##methods dealing with teams

  #for calling in index.html and other views
  def team_name
    self.team == nil ? "" : self.team.name
  end

  def is_member_of(team)
    return self.team == team
  end

  def is_leader_of(team)
    return team.leader == self
  end

  def has_a_team
    return self.team != nil
  end

  def is_a_leader
    return self.team != nil && self.team.leader == self
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  @@registration_code = "Michael"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # def update
  #   self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)


  #   # custom logic
  #   if params[:current_password].blank?
  #     resource.update_without_password(params)
  #   else
  #     resource.update_with_password(params)
  #   end

  #   # standart devise behaviour
  #   if result
  #     if is_navigational_format?
  #       if resource.respond_to?(:pending_reconfirmation?) && resource.pending_reconfirmation?
  #         flash_key = :update_needs_confirmation
  #       end
  #       set_flash_message :notice, flash_key || :updated
  #     end
  #     sign_in resource_name, resource, :bypass => true
  #     respond_with resource, :location => after_update_path_for(resource)
  #   else
  #     clean_up_passwords resource
  #     respond_with resource
  #   end
  # end

  # DELETE /resource
  def destroy
    user = User.find(params[:toDelete])

    users_team = user.team
    if user.is_a_leader && users_team.members.length == 1
      users_team.destroy
    elsif user.is_a_leader && users_team.members.length > 1
      team_members_without_leader = users_team.members - [users_team.leader]
      users_team.user_id = team_members_without_leader[0].id
      users_team.save!
    end

    user.destroy

    redirect_to users_path, flash: {notice: "User was successfully deleted"}
  end

  def update_resource(resource, params)
    if params[:password].blank? && params[:password_confirmation].blank? && params[:email].eql?(@user.email)
      params.delete(:current_password)
      resource.update_without_password(params)
    else
      super
    end
  end
  
  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :home
  before_action :authenticate_admin, only: [:admin_index, :registration_code, :admin_code, :download_roster]
  before_action :validate_change_code_params, only: [:change_code]

  helper_method :sort_column, :sort_direction

  def authenticate_admin
    unless current_user.admin?
      redirect_to home_path
    end
  end

  def validate_change_code_params
    redirect_to home_path unless Code.valid_access_levels.include? params[:access_level]
  end

  def home
    flash.keep

    if current_user
      redirect_to user_path(current_user)
    else
      redirect_to new_user_session_path
    end
  end

  def auto_complete(users)
    @autoComplete = Array.new()
    users.each do |user|
      s = user.first
      s = s + " " + user.last
      @autoComplete.push(s)
    end
  end

  def index
    @message = "Hello, #{current_user.first}!"
    if @users.nil? || params[:search].nil?
      @users = User.all
    end
    auto_complete(@users)

    @users = current_user.search(params[:search], false) || User.order(sort_column + ' ' + sort_direction)
  end

  def admin_index
    @message = "Hello, #{current_user.first}!"
    @users = (@users.nil? || params[:search].nil?) ? User.all : ""
    auto_complete(@users)
    @users = current_user.search(params[:search], true) || User.order(sort_column + ' ' + sort_direction)
  end

  def show
    @message = "Hello, #{current_user.first}!"
    @user = find_curr
    @emailName = @user.email.split("@").first
    @emailHost = @user.email.split("@").last.split(".").first
    @emailDomain = @user.email.split(".").last
  end

  def edit
  end

  def leave
    @user = find_curr
    if !@user.team.nil?
      if @user.team.user_id == params[:id].to_i
        flash[:alert] = "Please ensure that there's another admin for this team."
      else
        @user.team = nil
        @user.save
      end
    end
    redirect_to user_path(@user)
  end

  def change_code
    newCode = params[:registration_code] || params[:admin_code] || params[:superadmin_code]

    begin
      flash[:notice] = User.change_code(params[:access_level], newCode)
    rescue ActiveRecord::RecordInvalid => e
      flash[:notice] = Code.code_uniqueness_message
    end

    redirect_to users_admin_path
  end

  def spreadsheet
    @users =  User.all

    respond_to do |format|
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"EAB_roster#{Date.today}.xlsx\""
      }
    end
  end

  def clear
    @users = User.where(code: Code.regular_code)
    @teams = Team.destroy_all
    @users.each do |user|
      user.delete
    end
    redirect_to users_admin_path
  end

  def make_admin
    @user = find_curr
    @user.code = Code.admin_code
    @user.save!
    redirect_to user_path(@user)
  end

  def make_super
    @user = find_curr
    @user.code = Code.superadmin_code
    @user.save!
    redirect_to user_path(@user)
  end

  def make_regular
    @user = find_curr
    @user.code = Code.regular_code
    @user.save!
    redirect_to user_path(@user)
  end


  def find_curr
    User.find(params[:id])
  end

  private
  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "first"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_display_users.html.haml
%div.container
  - @users.each_slice(4) do |slice|
    %div.row
      - slice.each do |user|
        %div.user-tile-wrapper.col-sm-12.col-md-3

          %div.user-tile

            %a.user-tile-link{:href => user_path(user)}
              %div.user-tile-img{:style => "background-image: url('#{user.image.url}')"}

                %div.user-tile-img-overlay
                  %p= "More about #{user.first} #{user.last}"

              %div.user-tile-info

                - if user.team_name.blank?
                  - team = "No team"
                - else
                  - team = user.team_name

                - if user.major
                  - major = user.major
                - else
                  - major = "No major"

                - if user.year
                  - year = user.year
                - else
                  - year = "No year"

                %p.team= "#{team}"
                %h4= "#{user.first} #{user.last}"
                %p.user-about.year= "#{major}"
                %p.user-about.year= "#{year}"
                %p.user-about.skillset= "Skills: #{user.skillset}"

            %div.user-contact
              - if user.facebook && !user.facebook.empty?
                %a.contact.fb{:target => "_blank", :href => "https://www.#{user.facebook}"}
                  %i.fab.fa-lg.fa-facebook-square
              - else
                %a.contact.fb.inactive
                  %i.fab.fa-lg.fa-facebook-square

              - if user.linkedinLstring && !user.linkedinLstring.empty?
                %a.contact.linkedin{:target => "_blank", :href => "https://www.#{user.linkedinLstring}"}
                  %i.fab.fa-lg.fa-linkedin
              - else
                %a.contact.linkedin.inactive
                  %i.fab.fa-lg.fa-linkedin

            - if promotable
              - if current_user.is_leader_of(@team)
                %div.container.title-container
                  = form_tag(promote_to_leader_path(team_id: @team.id, user_id: user.id), :method => 'PATCH', class: %w[form form-inline my-2 my-lg-0]) do
                    = submit_tag "Promote to Leader", name: nil, class: %w[button btn btn-outline-success my-2 my-sm-0], data: { confirm: "Are you sure?" }
                %div.container.title-container
                  = form_tag(leave_team_path(user), class: %w[form form-inline my-2 my-lg-0]) do
                    = submit_tag "Kick from Team", name: nil, class: %w[button btn btn-outline-success my-2 my-sm-0], data: { confirm: "Are you sure?" }

app/views/users/_flash_messages.html.haml
- flash.each do |type, msg|
  %div{:class => "alert alert-#{type == :notice ? "success" : type} fadeout", "data-dismiss" => "alert"}
    %button.close &times;
    = msg if msg.is_a?(String)

app/views/users/_footer.html.haml
%footer.text-muted
  .container
    %p.float-right
      %a{:href => "#"} Back to top

    %p Entrepreneurs at Berkeley

app/views/users/_nav_bar.html.haml
= javascript_include_tag "application"

%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %div.container
    %a.navbar-brand{:href => "https://entrepreneurs.berkeley.edu"} Entrepreneurs@Berkeley
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon

    #navbarSupportedContent.collapse.navbar-collapse

      %ul.navbar-nav.mr-auto

        %li.nav-item
          %a.nav-link{:href => announcements_path} Dashboard

        %li.nav-item
          %a.nav-link{:href => teams_path} Teams

        - if current_user.try(:admin?)
          %li.nav-item
            %a.nav-link{:href => users_path, :method => :get} Members
        - else
          %li.nav-item
            %a.nav-link{:href => users_path, :method => :get} Members

        - if current_user.try(:admin?)
          %li.nav-item
            %a.nav-link{:href => users_admin_path, :method => :get} Members (Admin View)

      %ul.navbar-nav.ml-auto

        - if !user_signed_in?
          %li.nav-item
            %a.nav-link{:href => new_user_session_path} Login

          %li.nav-item
            %a.nav-link{:href => new_user_registration_path} Create New Account

        - if user_signed_in?
          %li.nav-item
            %a.nav-link#user-link{:href => user_path(current_user)}
              = image_tag current_user.image.url
              #{current_user.first} #{current_user.last}

          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              More
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
              %a.dropdown-item{:href => user_path(current_user)} View Profile
              %a.dropdown-item{:href => edit_page_path(current_user)} Edit Profile
              - if current_user.has_a_team
                .dropdown-divider
                %a.dropdown-item{:href => team_path(:id => current_user.team_id)} View Team
                - if current_user.is_a_leader
                  %a.dropdown-item{:href => edit_team_path(:id => current_user.team_id)} Edit Team
              .dropdown-divider
              %a.dropdown-item{:href => destroy_user_session_path, "data-method" => "delete"} Logout

app/views/users/admin_index.html.haml
.content
  = render :partial => 'users/nav_bar', :locals => { :current_user => current_user }

.content
  = render :partial => 'users/flash_messages', :locals => { :flash => flash }

%div.container.title-container
  %h2 Admin Duties
  = form_tag(change_code_path(access_level: "regular"), :method => 'PATCH') do
    = text_field_tag(:registration_code, Code.regular_code)
    = submit_tag "Change Regular Access Code", name: nil

  = form_tag(change_code_path(access_level: "admin"), :method => 'PATCH') do
    = text_field_tag(:admin_code, Code.admin_code)
    = submit_tag "Change Admin Access Code", name: nil

  - if current_user.code == Code.superadmin_code
    = form_tag(change_code_path(access_level: "superadmin"), :method => 'PATCH') do
      = text_field_tag(:superadmin_code, Code.superadmin_code)
      = submit_tag "Change Superadmin Access Code", name: nil

.container.form-container
  .row
    .field.col-md-5
      = button_to "Export Members as XLSX", users_spreadsheet_path(format: "xlsx"), class: %w[button btn btn-outline-success], method: :get
    .field.col-md-5
      - if current_user.code == Code.superadmin_code
        = button_to "Delete All Regular Members", users_clear_path, class: %w[button btn btn-outline-success], :data => {:confirm => 'Are you sure?'}, method: :get


%div.container.title-container
  %h2 Members

  = form_tag(users_admin_path, :method => 'GET', class: %w[form form-inline my-2 my-lg-0]) do
    = text_field_tag(:search, params[:search], :placeholder => "ex. Michael", class: %w[input form-control], :id => "searchField")
    = submit_tag "Search", name: nil, class: %w[button btn btn-outline-success my-2 my-sm-0]
  :javascript
    var list = #{raw @autoComplete};
    var json = [];
    for (var i = 0; i < list.length; i++) {
      var dict = {};
      dict["name"] = list[i];
      json.push(dict)
    }
    var options = {
      data: json,
      getValue: "name",
      list: {
        match: {
          enabled: true
        }
      }
    };
      $("#searchField").easyAutocomplete(options);

  %table.table-striped.col-md-10#users
    %thead
      %tr
        %th= sortable "first", "First"
        %th= sortable "last", "Last"
        %th= sortable "email", "Email"
        %th= sortable "team", "Team"
        %th Team-Leader?
        %th Skillset
        %th= sortable "sid", "SID"
        %th= sortable "year", "Year"
        %th= sortable "major", "Major"
        %th Facebook
        %th LinkedIn
        %th Privileges

    %tbody
      - @users.each do |user|
        %tr
          %td= link_to "#{user.first}", user_path(user)
          %td= link_to "#{user.last}", user_path(user)
          %td= link_to "#{user.email}", user_path(user)
          %td= user.team_name
          - if user.is_a_leader
            %td Yes
          - else
            %td No
          %td= user.skillset
          %td= user.sid
          %td= user.year
          %td= user.major
          %td= user.facebook
          %td= user.linkedinLstring
          %td= user.access
          %td= link_to "More about #{user.first}", user_path(user)

app/views/users/create.html.haml
%h1 Create Account Page

= form_tag create_path do

  = label :user, :email, 'Email'
  = text_field :email, 'email'

  = label :user, :password, 'Password'
  = password_field :password, 'password'

  = submit_tag 'Create Account'

= link_to 'Back', home_path

app/views/users/forgot.html.haml
%h1 Forgot Password

= form_tag forgot_path do

  = label :user, :username, 'Username'
  = text_field :user, 'username'

  = submit_tag 'Submit'

= link_to 'Back', create_page_path

app/views/users/home.html.haml
.content
  = render :partial => 'users/nav_bar', :locals => { :current_user => current_user }


%ul#details
  = @message

app/views/users/index.html.haml
.content
  = render :partial => 'users/nav_bar', :locals => { :current_user => current_user }


.content
  = render :partial => 'users/flash_messages', :locals => { :flash => flash }


%div.container.title-container
  %h2 Members

  = form_tag(users_path, :method => 'GET', class: %w[form form-inline my-2 my-lg-0]) do
    = text_field_tag(:search, params[:search], :placeholder => "ex. Michael", class: %w[input form-control], :id => "searchField")
    = submit_tag "Search", name: nil, class: %w[button btn btn-outline-success my-2 my-sm-0]
  :javascript
    var list = #{raw @autoComplete};
    var json = [];
    for (var i = 0; i < list.length; i++) {
      var dict = {};
      dict["name"] = list[i];
      json.push(dict)
    }
    var options = {
      data: json,
      getValue: "name",
      list: {
        match: {
          enabled: true
        }
      }
    };
    $("#searchField").easyAutocomplete(options);

%div.container.sort-container

  .dropdown.show
    %a#dropdownMenuLink.btn.btn-secondary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
      Sort By
    .dropdown-menu{"aria-labelledby" => "dropdownMenuLink"}
      .container
        %h6= sortable "first", "First"
        %h6= sortable "last", "Last"
        %h6= sortable "team", "Team"
        %h6= sortable "major", "Major"
        %h6= sortable "year", "Year"


.content
  = render :partial => 'users/display_users', :locals => { :@users => @users, :promotable => false, :current_user => nil, :@team => nil}

app/views/users/login.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %div.container
    %a.navbar-brand{:href => home_path} Entrepreneurs@Berkeley
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon

    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto

        %li.nav-item
          %a.nav-link{:href => destroy_user_session_path, "data-method" => "delete"} Logout

%h1 Login Page

= form_tag login_path do

  = label :user, :email, 'Email'
  = text_field :email, 'email'

  = label :user, :password, 'Password'
  = password_field :password, 'password'

  = submit_tag 'Login'

= link_to 'Back', home_path
= link_to 'Forgot Password', forgot_page_path
= link_to 'Create New Account', create_page_path

app/views/users/show.html.haml
.page_format{:style => " margin-left: 15px;"}

.content
  = render :partial => 'users/nav_bar', :locals => { :current_user => current_user }

.content
  = render :partial => 'users/flash_messages', :locals => { :flash => flash }

%div.profile-container.container
  %div.row{ style: 'padding-top: 20px;'}
    %div.profile-side-wrapper.col-2
      %table
        %tr
          %td.profPic{ style: 'max-height: 200px; max-width: 200px; padding-bottom: 10px;'}
            = image_tag(@user.image.url(:medium), :style => "border-radius: 50%; max-height: 200px; max-width:200px;", class:"img-responsive img-circle", alt: "missing.png")

        %tr.firstName{ style: 'font-size: 18px; text-align: center;' }
          %td.profileName{ style: 'font-size: 18px; text-align: center;' }
            %h3 #{@user.first} #{@user.last}

        %tr
          %td.profileEmail{ style: 'font-size: 14px; text-align: center;' }
            - if current_user.admin?
              = @user.email
              - if @user.code == Code.regular_code
                = "Standard User"
              - elsif @user.code == Code.admin_code
                = "Admin"
              - else
                = "Superadmin"
            - else
              = "      "
              = @emailName
              = image_tag "atSymbol.jpg", :size => "50x50"
              = @emailHost
              = image_tag "period.png",  :size => "50x50"
              = @emailDomain

        %tr
          %td.socialMedia{ style: 'font-size: 2.5rem; text-align: center;' }
            - if @user.facebook && !@user.facebook.empty?
              %a.contact.fb{:target => "_blank", :href => "https://www.#{@user.facebook}"}
                %i.fab.fa-lg.fa-facebook-square
            - else
              %a.contact.fb.inactive
                %i.fab.fa-lg.fa-facebook-square

            - if @user.linkedinLstring && !@user.linkedinLstring.empty?
              %a.contact.linkedin{:target => "_blank", :href => "https://www.#{@user.linkedinLstring}"}
                %i.fab.fa-lg.fa-linkedin
            - else
              %a.contact.linkedin.inactive
                %i.fab.fa-lg.fa-linkedin

    %div.profile-filler-wrapper.col-1
    %div.profile-main-wrapper.col-9
      %table
        %tr
          %td.profileMajor{ style: 'font-size: 20px;' }
            Major: #{@user.major}
        %tr
          %td.profileYear{ style: 'font-size: 20px;' }
            Year:
            = @user.year
        %tr
          %td.profileTeam{ style: 'font-size: 20px;' }
            Team:
            = @user.team_name
        %tr
          %td.profileSkills{ style: 'font-size: 20px;' }
            Skills: #{@user.skillset}


    %div.profile-button-wrapper.col-16
      - if current_user.id == @user.id
        = link_to 'Edit Account', edit_page_path(@user), class: %w[button btn btn-outline-success]
        &nbsp
      - if current_user.id == @user.id && current_user.has_a_team
        = button_to "Leave Team", leave_team_path(@user), class: %w[button btn btn-outline-success], data: { confirm: "Are you sure?" }
        &nbsp
      - if current_user.admin?
        = button_to "Delete User", users_path(@user), class: %w[button btn btn-outline-success], params: {:toDelete => @user.id},data: { confirm: "Are you sure?" }, method: :delete
        &nbsp
      - if current_user.code == Code.superadmin_code
        - if @user.code != Code.admin_code
          = form_tag(make_admin_path, :method => 'PATCH', class: %w[form form-horizontal]) do
            = submit_tag "Make Admin", name: nil, class: %w[button btn btn-outline-success], data: { confirm: "Are you sure?" }
          &nbsp
        - if @user.code == Code.admin_code
          = form_tag(make_super_path, :method => 'PATCH', class: %w[form form-horizontal]) do
            = submit_tag "Make Superadmin", name: nil, class: %w[button btn btn-outline-success], data: { confirm: "Are you sure?" }
          &nbsp
        - if @user.code != Code.regular_code
          = form_tag(make_regular_path, :method => 'PATCH', class: %w[form form-horizontal]) do
            = submit_tag "Make Regular", name: nil, class: %w[button btn btn-outline-success], data: { confirm: "Are you sure?" }
          &nbsp